### ISSUE TITLE
Unexpected token in JSON returned from /api/mcu/stats endpoint

### ISSUE THREAD

**Issue by bbuchalter** [jstefanop/apolloapi#4]
Hello!

I just got my FutureBit Apollo BTC. On the dashboard, I'm seeing this message:

![image](https://user-images.githubusercontent.com/540762/126087411-81de6e20-b015-46ad-9e71-17ca3e45acf4.png)

When I `tail -f /var/log/syslog` I see the following errors:

```
Jul 19 00:28:19 futurebit-btc node[1829]: {"name":"app","hostname":"futurebit-btc","pid":1829,"cid":"da1d0a05-3675-45af-9516-da99416c43b6","seq":0,"method":"api/mcu/stats","stack":[{"cid":"da1d0a05-3675-45af-9516-da99416c43b6","seq":0,"method":"api/mcu/stats"}],"level":50,"user":{"iat":1626652665,"aud":"auth","sub":"apollouser"},"source":"auto","when":"after","err":{"message":"Unexpected token \n in JSON at position 299","name":"SyntaxError","stack":"SyntaxError: Unexpected token \n in JSON at position 299\n    at JSON.parse (<anonymous>)\n    at /opt/apolloapi/src/store/api/mcu/mcuStats.js:26:31\n    at ChildProcess.exithandler (child_process.js:299:7)\n    at ChildProcess.emit (events.js:315:20)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Socket.<anonymous> (internal/child_process.js:439:11)\n    at Socket.emit (events.js:315:20)\n    at Pipe.<anonymous> (net.js:673:12)"},"ms":1525,"msg":"after_api/mcu/stats (1525ms)","time":"2021-07-19T00:28:19.351Z","v":0}
```

I'm not sure where to continue debugging. Any advice?

**Comment by bbuchalter** [comment]
After reading the stack trace more carefully, I saw the reference to `/opt/apolloapi/src/store/api/mcu/mcuStats.js:26:31`.

This seemed to invoke this command: `/opt/apolloapi/src/store/api/mcu/../../../../backend/os_stats` which returned the following:
```
{
  "hostname": "futurebit-btc",
  "operatingSystem": "Ubuntu 20.04 focal",
  "uptime": "2021-07-17 13:51:29",
  "loadAverage": "1.65 1.27 0.96 2/283 86349",
  "architecture": "aarch64",
  "temperature": "65000",
  "minerTemperature": "0",
  "minerFanSpeed": "0",
  "activeWifi": "Wired connection 1
tailscale0",
  "network": [{
      "name": "eth0",
      "address": "192.168.20.177",
      "mac": "9a:7b:37:3d:43:de"
  }, {
      "name": "wlan0",
      "address": "",
      "mac": "b0:02:47:b9:f5:c3"
  }],
  "memory":
  {
    "total": 3956112,
    "available": 2618460,
    "used": 3921420,
    "cache": 2583768,
    "swap": 763572
  },
  "cpu":
  {
    "threads": 6,
    "usedPercent": 8
  },
  "disks": [
    {"total":14899824,
"used":5656684,
"mountPoint":"/"},
{"total":49584,
"used":17048,
"mountPoint":"/var/log"},
{"total":479669928,
"used":218153456,
"mountPoint":"/media/nvme"}
  ],
  "bfgminerLog": ""
}
```

Passing that into https://jsonlint.com/ I can now see the error:
```
Error: Parse error on line 10:
..."0",	"activeWifi": "Wired connection 1
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

Looks like it doesn't like the new line here...

**Comment by bbuchalter** [comment]
Looks like my use of tailscale to access the node remotely is interfering with the output of `nmcli`:

```
root@futurebit-btc:/opt/apolloapi# nmcli -t -f name c show --active
Wired connection 1
tailscale0
```

Replacing the new line with a comma resolved the issue:
```
diff --git a/backend/os_stats b/backend/os_stats
index c2637eb..901474a 100755
--- a/backend/os_stats
+++ b/backend/os_stats
@@ -34,7 +34,7 @@ if [ -f "/sys/devices/virtual/thermal/thermal_zone0/temp" ]; then
 else
   TEMP="0"
 fi
-ACTIVE_WIFI=$(nmcli -t -f name c show --active)
+ACTIVE_WIFI=$(nmcli -t -f name c show --active | tr '\n' ',')
```

However, it leads to slightly strange output in the UI, but the error is gone both in the logs and the UI.

![image](https://user-images.githubusercontent.com/540762/126088032-7af52a1a-bfcc-41da-be01-a243a80dc0d2.png)

Another strategy could be to collect more output information:
```
root@futurebit-btc:/opt/apolloapi# nmcli c show --active
NAME                UUID                                  TYPE      DEVICE     
Wired connection 1  9d2a951a-62da-348b-9347-c08ece161aeb  ethernet  eth0       
tailscale0          8a24dc07-d08a-4c5d-8d01-63a33abac407  tun       tailscale0 
```

And then `grep -v tun` and then `cut` to grab the name.

Happy to open and or approve a PR if that's helpful.

**Comment by jstefanop** [comment]
Thanks for the debug, this is a known issue. Next update should have this fixed. 

@michelem09 anything here that has not been fixed in dev yet?

**Comment by michelem09** [comment]
Thanks @bbuchalter I will check this ASAP

**Comment by michelem09** [comment]
So yes, this is due to multiple active wifi detected by `nmcli` command, I didn't consider this scenario. I will commit a patch for this.
